DROP TABLE IF EXISTS ORDER_HISTORY;
DROP TABLE IF EXISTS WISH_LIST;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS HOT_DEALS;

CREATE TABLE USERS(
    ID VARCHAR(15),
    Password VARCHAR(15) NOT NULL,
    enabled boolean NOT NULL
);

CREATE TABLE authorities (
    ID varchar(50) NOT NULL,
    AUTHORITY varchar(50) not null,
    foreign key (ID) references users (ID)
);

CREATE TABLE ORDER_HISTORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(15) NOT NULL,
    USER_RATING INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE ITEMS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_GLOBAL_RATING INT DEFAULT 0,
    ORDER_ID INT,
    ON_SALE BOOLEAN,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_HISTORY(ID)
);

CREATE TABLE WISH_LIST (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(15) NOT NULL,
    ITEM_LIST VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE HOT_DEALS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR (15),
    ITEM_LIST VARCHAR(50),
    CREATED_DATE TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
